"""EQY adapter — formal equivalence between the baseline and a candidate.

``equiv.eqy`` is the only file in the project where the two RTL trees meet. The
equivalence relation is written into it explicitly rather than assumed, because
"formal equivalence" without a stated relation, reset assumption, and proof
scope is not a claim anyone can check.
"""

from __future__ import annotations

from pathlib import Path

from orchestrator.adapters.base import ToolInvocation
from orchestrator.config import ProjectConfiguration
from orchestrator.schemas.common import write_text


def build_eqy_script(
    config: ProjectConfiguration,
    gold_files: list[Path],
    gate_files: list[Path],
    out_dir: Path,
    script_path: Path,
) -> str:
    """Compose ``equiv.eqy``.

    ``gold`` is always the immutable baseline and ``gate`` is always the
    candidate copy. The direction is fixed so a mis-wired call cannot silently
    prove the candidate against itself.
    """
    top = config.equivalence.gold_top or config.design.top_module
    relation = config.equivalence.relation

    gold_reads = "\n".join(f"read_verilog {p.as_posix()}" for p in gold_files)
    gate_reads = "\n".join(f"read_verilog {p.as_posix()}" for p in gate_files)

    blackbox_lines = "\n".join(
        f"blackbox {name}" for name in config.equivalence.blackboxes
    )

    script = f"""\
# Generated by orchestrator/adapters/eqy.py -- do not edit by hand.
#
# Equivalence relation : {relation}
# Reset assumption     : {config.equivalence.reset_assumption or "none declared"}
# Proof scope          : whole design, partitioned by EQY
#
# UNKNOWN and TIMEOUT results are recorded as such by
# orchestrator/parsers/eqy_status.py and are never reported as PASS.

[options]
splitnets off
insbuf on

[gold]
{gold_reads}
prep -top {top}
{blackbox_lines}

[gate]
{gate_reads}
prep -top {top}
{blackbox_lines}

# Strategies are tried in order per partition. Both use EQY's "sat" engine,
# which runs Yosys's built-in SAT solver with temporal induction and needs no
# external SMT binary -- the ORFS image ships none (no bitwuzla, yices, z3 or
# boolector), so an SMT-based strategy would be unrunnable here. "depth" is a
# per-strategy option; EQY's [options] section accepts only splitnets and
# insbuf, and rejects anything else outright.
[strategy simple]
use sat
depth 10

[strategy deep]
use sat
depth 25
"""
    write_text(script_path, script)
    return script


def eqy_invocation(
    config: ProjectConfiguration,
    gold_files: list[Path],
    gate_files: list[Path],
    out_dir: Path,
    timeout_s: int | None = None,
) -> ToolInvocation:
    """Describe an EQY run.

    ``-f`` forces a clean work directory: a stale PASS marker from a previous
    candidate is exactly the kind of artifact that would produce a false result.
    """
    script_path = out_dir / "equiv.eqy"
    build_eqy_script(config, gold_files, gate_files, out_dir, script_path)
    binary = config.tool_binary("eqy", "eqy")
    work_dir = out_dir / "equiv"
    return ToolInvocation(
        tool="eqy",
        command=[binary, "-f", "-d", work_dir.as_posix(), script_path.as_posix()],
        cwd=out_dir,
        log_dir=out_dir,
        log_name="eqy",
        timeout_s=timeout_s or config.run_policy.timeout("eqy", 3600),
        expected_outputs={"log": work_dir / "logfile.txt"},
        fixture_key="eqy",
    )
