"""OpenSTA adapter — static timing analysis.

Two details in the generated Tcl are load-bearing:

* ``report_checks -format full_clock_expanded`` — the default format omits the
  launch and capture clock edges. Without those two fields a path cannot be
  classified as same-domain or cross-domain, which would quietly remove the
  multi-clock analysis the project is built around.
* ``report_checks -unconstrained`` into its own file — so that "zero violations"
  can be distinguished from "nothing was constrained". Those two states produce
  an identical headline number and mean opposite things.
"""

from __future__ import annotations

from pathlib import Path

from orchestrator.adapters.base import ToolInvocation
from orchestrator.config import ProjectConfiguration
from orchestrator.schemas.common import write_text

#: How many worst paths to report. Enough to give the request builder a choice,
#: small enough that the report stays parseable and the context stays bounded.
PATH_GROUP_COUNT = 10


def build_sta_script(
    config: ProjectConfiguration,
    netlist: Path,
    out_dir: Path,
    script_path: Path,
) -> str:
    """Compose ``sta.tcl``."""
    liberty = config.liberty_path()
    sdc = config.sdc_path()

    lines = [
        "# Generated by orchestrator/adapters/opensta.py -- do not edit by hand.",
        f"# project: {config.project_id}   top: {config.design.top_module}",
        "",
        f"read_liberty {liberty.as_posix()}",
        f"read_verilog {netlist.as_posix()}",
        f"link_design {config.design.top_module}",
        f"read_sdc {sdc.as_posix()}",
        "",
        "# Clock inventory. Recorded so a disappearing clock is detectable.",
        f"set clk_fh [open {(out_dir / 'clocks.rpt').as_posix()} w]",
        "foreach clk [all_clocks] {",
        "    puts $clk_fh \"clock [get_name $clk] period [get_property $clk period]\"",
        "}",
        "close $clk_fh",
        "",
        "# Headline slack.",
        f"set wns_fh [open {(out_dir / 'wns_tns.rpt').as_posix()} w]",
        "puts $wns_fh \"wns [sta::worst_slack -max]\"",
        "puts $wns_fh \"tns [sta::total_negative_slack -max]\"",
        "close $wns_fh",
        "",
        "# Detailed paths. full_clock_expanded keeps launch/capture edges.",
        "# OpenSTA uses native `> file` redirection, not Synopsys `redirect {}`.",
        "report_checks -path_delay max \\",
        "              -format full_clock_expanded \\",
        f"              -group_count {PATH_GROUP_COUNT} \\",
        "              -slack_max 0.0 \\",
        f"              -digits 4 > {(out_dir / 'timing.rpt').as_posix()}",
        "",
        "# Unconstrained endpoints get their own file so that 'no violations'",
        "# cannot be confused with 'nothing was checked'.",
        f"report_checks -unconstrained -format full -digits 4 > {(out_dir / 'unconstrained.rpt').as_posix()}",
        "",
        "exit 0",
        "",
    ]
    script = "\n".join(lines)
    write_text(script_path, script)
    return script


def sta_invocation(
    config: ProjectConfiguration,
    netlist: Path,
    out_dir: Path,
    timeout_s: int | None = None,
) -> ToolInvocation:
    """Describe an OpenSTA run."""
    script_path = out_dir / "sta.tcl"
    build_sta_script(config, netlist, out_dir, script_path)
    binary = config.tool_binary("opensta", "sta")
    return ToolInvocation(
        tool="opensta",
        command=[binary, "-no_splash", "-exit", script_path.as_posix()],
        cwd=out_dir,
        log_dir=out_dir,
        log_name="opensta",
        timeout_s=timeout_s or config.run_policy.timeout("sta", 900),
        expected_outputs={
            "timing": out_dir / "timing.rpt",
            "wns_tns": out_dir / "wns_tns.rpt",
            "clocks": out_dir / "clocks.rpt",
        },
        fixture_key="opensta",
    )
