"""ORFS adapter — the authoritative physical run.

Nebula does not generate ORFS itself. It generates the one design-specific file
ORFS needs, ``config.mk``, and invokes the flow. Everything in that file except
``VERILOG_FILES`` is identical between the baseline and every candidate, which
is what keeps the physical comparison honest.

ORFS requires an absolute ``DESIGN_CONFIG`` path. That absolutisation happens
here, at invocation time, and nowhere else — the manifest and every stored
record keep relative paths so the project stays portable.
"""

from __future__ import annotations

from pathlib import Path

from orchestrator.adapters.base import ToolInvocation
from orchestrator.config import ProjectConfiguration
from orchestrator.schemas.common import write_text


def build_config_mk(
    config: ProjectConfiguration,
    rtl_files: list[Path],
    out_dir: Path,
    config_path: Path,
) -> str:
    """Compose ``config.mk`` for one design variant.

    Args:
        rtl_files: baseline RTL for the baseline run, candidate RTL for a
            candidate run. This is the *only* value that differs between them.
    """
    verilog = " \\\n                     ".join(p.as_posix() for p in rtl_files)
    lef_lines = " ".join(config.resolve(p).as_posix() for p in config.platform.lef)

    script = f"""\
# Generated by orchestrator/adapters/orfs.py -- do not edit by hand.
#
# Every variable below except VERILOG_FILES is identical for the baseline and
# for each candidate. That is what makes the physical comparison meaningful.

export DESIGN_NICKNAME = {config.project_id}
export DESIGN_NAME     = {config.design.top_module}
export PLATFORM        = {config.platform.platform_id}

export VERILOG_FILES = {verilog}

export SDC_FILE      = {config.sdc_path().as_posix()}
export LIB_FILES     = {config.liberty_path().as_posix()}
export LEF_FILES     = {lef_lines}

export CORE_UTILIZATION   = 40
export PLACE_DENSITY      = 0.60
export CORE_ASPECT_RATIO  = 1

# Output goes inside the Nebula run tree, not into the ORFS checkout, so a run
# can be archived whole.
export WORK_HOME = {out_dir.as_posix()}
"""
    write_text(config_path, script)
    return script


def orfs_invocation(
    config: ProjectConfiguration,
    rtl_files: list[Path],
    out_dir: Path,
    timeout_s: int | None = None,
) -> ToolInvocation:
    """Describe an ORFS run."""
    config_path = out_dir / "config.mk"
    build_config_mk(config, rtl_files, out_dir, config_path)

    entry = config.toolchain.tools.get("orfs")
    flow_dir = (
        config.resolve(entry.flow_dir)
        if entry and entry.flow_dir
        else config.project_root / "OpenROAD-flow-scripts" / "flow"
    )
    binary = config.tool_binary("orfs", "make")

    return ToolInvocation(
        tool="orfs",
        # ORFS insists on an absolute DESIGN_CONFIG; this is the only place in
        # the codebase that absolutises a project path.
        command=[binary, f"DESIGN_CONFIG={config_path.resolve().as_posix()}"],
        cwd=flow_dir,
        log_dir=out_dir,
        log_name="orfs",
        timeout_s=timeout_s or config.run_policy.timeout("orfs", 14400),
        expected_outputs={"metadata": out_dir / "metadata-base.json"},
        fixture_key="orfs",
    )
