"""Yosys adapter — elaboration, synthesis, and the source-mapping bridge.

The single most important line this adapter emits is ``write_json``. Yosys
annotates cells and wires with ``src`` attributes of the form
``dsp_core.v:41.20-41.55``, and that JSON is the only mechanical link between a
gate on a critical path and the RTL line that produced it. Without it, "trace
the path back to source" is pattern-matching on net names.
"""

from __future__ import annotations

from pathlib import Path

from orchestrator.adapters.base import ToolInvocation
from orchestrator.config import ProjectConfiguration
from orchestrator.schemas.common import write_text


def build_synth_script(
    config: ProjectConfiguration,
    rtl_files: list[Path],
    out_dir: Path,
    script_path: Path,
) -> str:
    """Compose ``synth.ys``.

    The script is fixed-form and generated only from the manifest. No part of it
    is ever supplied by the model — that is the reason patch application and
    script generation are separate stages.
    """
    liberty = config.liberty_path()
    defines = " ".join(f"-D{k}={v}" for k, v in config.design.defines.items())
    includes = " ".join(f"-I{config.resolve(d)}" for d in config.design.include_dirs)
    params = " ".join(
        f"-chparam {name} {value}" for name, value in config.design.parameters.items()
    )

    read_lines = [
        f"read_verilog {'-sv ' if path.suffix.lower() == '.sv' else ''}"
        f"{defines} {includes} {path.as_posix()}".replace("  ", " ").strip()
        for path in rtl_files
    ]

    lines = [
        "# Generated by orchestrator/adapters/yosys.py -- do not edit by hand.",
        f"# project: {config.project_id}   top: {config.design.top_module}",
        "",
        *read_lines,
        "",
        f"hierarchy -check -top {config.design.top_module} {params}".strip(),
        "proc; opt; fsm; opt; memory; opt",
        f"synth -top {config.design.top_module} -flatten",
        f"dfflibmap -liberty {liberty.as_posix()}",
        f"abc -liberty {liberty.as_posix()}",
        "setundef -zero",
        "opt_clean -purge",
        "",
        "# Give every cell a stable public name BEFORE either backend runs.",
        "# Without this, write_verilog renames non-public cells to _NNN_ while",
        "# write_json keeps Yosys's internal $abc$... names, so not one of the",
        "# cell names OpenSTA reports can be found in design.json and the whole",
        "# source-mapping stage resolves nothing. autoname derives the same",
        "# signal-based name for both, which is what makes the bridge possible.",
        "autoname",
        "",
        "# Mapped netlist for STA.",
        f"write_verilog -noattr {(out_dir / 'netlist.v').as_posix()}",
        "",
        "# Source-mapping bridge: carries src attributes back to RTL lines.",
        f"write_json {(out_dir / 'design.json').as_posix()}",
        "",
        "# Area and cell count.",
        f"tee -o {(out_dir / 'synth_stat.txt').as_posix()} stat -liberty {liberty.as_posix()}",
        "",
    ]
    script = "\n".join(lines)
    write_text(script_path, script)
    return script


def synth_invocation(
    config: ProjectConfiguration,
    rtl_files: list[Path],
    out_dir: Path,
    timeout_s: int | None = None,
) -> ToolInvocation:
    """Describe a Yosys synthesis run."""
    script_path = out_dir / "synth.ys"
    build_synth_script(config, rtl_files, out_dir, script_path)
    binary = config.tool_binary("yosys", "yosys")
    return ToolInvocation(
        tool="yosys",
        command=[binary, "-q", "-s", script_path.as_posix()],
        cwd=out_dir,
        log_dir=out_dir,
        log_name="yosys",
        timeout_s=timeout_s or config.run_policy.timeout("synth", 1800),
        expected_outputs={
            "netlist": out_dir / "netlist.v",
            "design_json": out_dir / "design.json",
            "stat": out_dir / "synth_stat.txt",
        },
        fixture_key="yosys",
    )
