// Accepted optimized auxiliary datapath for the ethmac5 qualification benchmark.
// Generated by Groq candidate cand_0001_06c207 and proved cycle-exact by EQY.

`default_nettype none

module nebula_aux_domain #(
    parameter integer WIDTH = 3328
) (
    input  wire              clk,
    input  wire              reset,
    input  wire              load,
    input  wire       [31:0] seed,
    output wire       [31:0] digest
);
    reg [WIDTH-1:0] state;

    wire [31:0] xor0 = state[31:0]    ^ state[63:32];
    wire [31:0] xor1 = state[95:64]   ^ state[127:96];
    wire [31:0] xor2 = state[159:128] ^ state[191:160];
    wire [31:0] xor3 = state[223:192] ^ state[255:224];
    wire [31:0] xor4 = xor0 ^ xor1;
    wire [31:0] xor5 = xor2 ^ xor3;
    wire [31:0] mix6 = xor4 ^ xor5;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            state <= {{(WIDTH-32){1'b0}}, 32'h1};
        end else begin
            state[WIDTH-1:32] <= state[WIDTH-33:0];
            if (load)
                state[31:0] <= seed;
            else
                state[31:0] <= mix6;
        end
    end

    assign digest = state[31:0] ^ state[WIDTH-1:WIDTH-32];
endmodule

`default_nettype wire
